version: '3.1'
services:
  app:
    build: .
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"